<?php 

require_once 'generic.class.inc';

class Emfl_Contact extends Emfl_Response_Generic {

  var $contactID;
  var $customerID; 
  var $userID;

  var $title;
  var $company;
  var $email; 
  var $phone;
  var $fax; 
  var $firstName; 
  var $lastName;
  var $dateOfBirth; 
  
  var $address1; 
  var $address2; 
  var $city; 
  var $state; 
  var $zipCode;
  var $country; 
  
  var $content1;
  var $content2;
  var $content3; 
  
  var $custom1; 
  var $custom2; 
  var $custom3; 
  var $custom4; 
  var $custom5; 
  var $custom6; 
  var $custom7; 
  var $custom8;
  var $custom9; 
  var $custom10; 
  var $custom11; 
  var $custom12; 
  var $custom13; 
  var $custom14; 
  var $custom15; 
  var $custom16; 
  var $custom17; 
  var $custom18; 
  var $custom19; 
  var $custom20; 
  
  var $dateAdded; 
  var $dateHeld; 
  var $dateModified; 
  var $dateSuppressed; 
  var $groupIDs; 
  var $held; 
  var $ipAddress;
  var $memo; 
  var $notes; 
  var $originalSource; 
  var $purl; 
  var $suppressed; 
  
}
