<?php 

require_once 'generic.class.inc';

class Emfl_Email extends Emfl_Response_Generic {
  
  var $approval;
  
  var $automation;
  
  var $content;
  
  var $dateAdded;
  
  var $dateModified;
  
  var $dateSent;
  
  var $deliveryType;
  
  var $emailID;
  
  var $fromAddress;
  
  var $fromName;
  
  var $metrics;
  
  var $parentEmailID;
  
  var $recipients;
  
  var $replyToAddress;
  
  var $replyToName;
  
  var $schedule;
  
  var $status;
  
  var $subject;
  
  var $templateID;
  
  var $title;
  
  var $userID;
  
}
